### ISSUE TITLE
Unable to use private key in the browser

### ISSUE THREAD

**Issue by xpepermint** [pedrouid/eccrypto-js#12]
The example from the README works in NodeJS but not in the browser. Try running the code below in the browser yourself:

```js
let eccryptoJS = window.eccryptoJS;
let publicKey = hexToString('...');
let privateKey = hexToString('...');
keyPair = { publicKey, privateKey};

const str = 'test message to encrypt';
const msg = eccryptoJS.utf8ToBuffer(str);

const encrypted = await eccryptoJS.encrypt(keyPair.publicKey, msg);
console.log('encrypted:', encrypted);
const decrypted = await eccryptoJS.decrypt(keyPair.privateKey, encrypted);
console.log('decrypted:', decrypted);
```
```js
function hexToString(hexString) {
	return new Uint8Array(hexString.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
}
```

Bonty: https://github.com/bitchan/eccrypto/issues/72

**Comment by pedrouid** [comment]
Im confused about this issue.... you are referring to a different library with a bounty.

Also your function `hexToString` is actually returning a Uint8Array

This library expect Buffer inputs and provides the methods for encoding these such as `hexToBuffer`

**Comment by xpepermint** [comment]
Yeah, it's actually already solved. Closing ...
